# Generated by Django 4.2.2 on 2023-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0027_canlıvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canlıvideo',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Kanal Adı'),
        ),
    ]
