# Generated by Django 4.1.7 on 2023-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0027_canlıvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canlıvideo',
            name='url',
            field=models.CharField(max_length=150, verbose_name='Url'),
        ),
    ]
