# Generated by Django 4.1.7 on 2023-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0028_alter_canlıvideo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canlıvideo',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Kanal Adı'),
        ),
        migrations.AlterField(
            model_name='canlıvideo',
            name='url',
            field=models.CharField(max_length=150, verbose_name='Url'),
        ),
    ]
