# Generated by Django 4.2.2 on 2023-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0006_alter_userinfo_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='end_package',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='package',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Paket Tipi'),
        ),
    ]
